name: space_xplore
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  # for adapting screen and font size.
  flutter_screenutil: ^5.9.3
  # State management
  flutter_bloc: ^8.1.3
  # Code generator (mainly used with cubit & retrofit)
  freezed: ^2.5.2
  freezed_annotation: ^2.4.2
  # for dependency injection
  get_it: ^7.6.4
  # Automatically generate code for converting to and from JSON by annotating Dart classes
  json_serializable: ^6.7.1
  json_annotation: ^4.9.0
  build_runner: ^2.4.11
  # Networking
  dio: ^5.3.3
  retrofit: ^4.0.3
  retrofit_generator: ^8.0.4
  pretty_dio_logger: ^1.3.1
  # for splash screen
  flutter_native_splash: ^2.3.5
  # An SVG rendering and widget library for Flutter, which allows painting
  flutter_svg: ^2.0.9
  # for bottom navigaton bar
  persistent_bottom_nav_bar: ^6.2.1
  # for fonts
  google_fonts: ^6.2.1
  # for connecting to the internet
  connectivity_plus: ^6.0.3
  # for caching images
  cached_network_image: ^3.3.1
  lottie: ^3.1.2
  # Animations
  flutter_staggered_animations: ^1.1.1
  # for crousal image
  carousel_slider: ^5.0.0
  # for webview
  webview_flutter: ^4.8.0
  # for utilities
  either_dart: ^1.0.0
  # for loading
  flutter_spinkit: ^5.2.1
  # for video player
  youtube_player_flutter: ^9.0.3
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lotties/

  
  # example:
  fonts:
    - family: Orbitron
      fonts:
        - asset: assets/fonts/Orbitron-Regular.ttf
        - asset: assets/fonts/Orbitron-Bold.ttf